#!/bin/sh
#Script to backup all the configurations in the /media/config folder
#The backup file will be created in /media/router/backup folder
DATA_FOLDER="/media/config"
BACKUP_FOLDER="/media/router/backup"
LOG_FILE="/opt/backup.log"

cd ${DATA_FOLDER};
docker compose stop $(docker ps --filter "label=needs.stop.for.backup=true" --format "{{.Names}}")
cd ${BACKUP_FOLDER};
sudo tar --ignore-failed-read -cvzf backup-$(date +%Y%m%d)_$(date +%H%M).tar.gz ${DATA_FOLDER} /etc/cron.daily /etc/cron.hourly
cd ${DATA_FOLDER};
docker compose up -d
echo $(date '+%Y-%m-%d %H:%M:%S') "CREATE - The Daily backup files has been created in ${BACKUP_FOLDER}" >> ${LOG_FILE};

HMOLDERTHAN4WEEKS=$(find $BACKUP_FOLDER -type f -mtime 28 -name '*.gz' | wc -l)
if  [ $HMOLDERTHAN4WEEKS > 1 ];
then
find $BACKUP_FOLDER -type f -mtime 28 -name '*.gz' -execdir rm -- {} +;
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - The backup files that older than 28 days has been deleted from $BACKUP_FOLDER" >> ${LOG_FILE};
else
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - No backup files that older than 28 days has been deleted" >> ${LOG_FILE};
fi
