#!/bin/sh
#Script to backup all the configurations in the /media/config folder

DIR="/media/config"

# Load .env file for variables
if [ -f "$DIR/.env" ]; then
  set -a
  . "$DIR/.env"
  set +a
fi

cd ${CONFIG_FOLDER};
docker compose stop $(docker ps --filter "label=needs.stop.for.backup=true" --format "{{.Names}}")
cd ${BACKUP_FOLDER};
sudo tar --ignore-failed-read -cvzf backup-$(date +%Y%m%d)_$(date +%H%M).tar.gz ${CONFIG_FOLDER} /etc/cron.daily /etc/cron.hourly
cd ${CONFIG_FOLDER};
docker compose up -d
echo $(date '+%Y-%m-%d %H:%M:%S') "CREATE - The Daily backup files has been created in ${BACKUP_FOLDER}" >> ${LOG_FILE};

HMOLDERTHAN4WEEKS=$(find $BACKUP_FOLDER -type f -mtime +28 -name '*.gz' | wc -l)
if [ $HMOLDERTHAN4WEEKS -gt 0 ]; then
find $BACKUP_FOLDER -type f -mtime +28 -name '*.gz' -execdir rm -- {} +;
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - The backup files older than 28 days has been deleted from $BACKUP_FOLDER" >> ${LOG_FILE};
else
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - No backup files older than 28 days to delete" >> ${LOG_FILE};
fi
