#!/bin/sh
#Script to backup Plex Database and Utorrent Server files hourly
DIR="/media/config"

# Load .env file for variables
if [ -f "$DIR/.env" ]; then
  set -a
  . "$DIR/.env"
  set +a
fi


cd $BACKUP_FOLDER;
sudo tar -cvzf backup-plexdb$(date +%Y%m%d)_$(date +%H%M).tar.gz ${CONFIG_FOLDER}/qbittorrent ${CONFIG_FOLDER}/tautulli ${CONFIG_FOLDER}/plex/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases
echo $(date '+%Y-%m-%d %H:%M:%S') "CREATE - The Hourly backup files has been created in /media/router/backup/" >> ${LOG_FILE};

HMOLDERTHAN24HOURS=$(find $BACKUP_FOLDER -type f -mmin +1440 -name 'backup-plexdb*.gz' | wc -l)
if [ $HMOLDERTHAN24HOURS -gt 0 ]; then
find $BACKUP_FOLDER -type f -mmin +1440 -name 'backup-plexdb*.gz' -execdir rm -- {} +;
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - The backup files older than 24 hours has been deleted from $BACKUP_FOLDER" >> ${LOG_FILE};
else
echo $(date '+%Y-%m-%d %H:%M:%S') "DELETE - No backup files older than 24 hours to delete" >> ${LOG_FILE};
fi